// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/helper/userhelper.go
//
// Generated by this command:
//
//	mockgen -source=pkg/helper/userhelper.go -destination=pkg/mock/mockhelper/helper_pkg_mock.go -package=mockrepo
//
// Package mockrepo is a generated GoMock package.
package mockrepo
